### PR TITLE
Update string_ref_test2.cpp

### PR DESCRIPTION
**Pull request by akumta**
For ticket# 10838

### CODE REVIEW

**Comment by mclow** [comment]
Can you tell me what compiler/library combination you're using?
[ Since `#include <cstring>` *should* get you `::strlen` ]

P.S.  I'm not opposed to making this change, btw.

**Comment by akumta** [comment]
I am using Oracle Solaris Studio 12.4 compiler,  and compile with 
-library=stlport4.

**Comment by Lastique** [comment]
@mclow No, <cstring> only provides std::strlen. ::strlen is provided be <string.h>. The fact that <c...> headers are implemented by a pack of using declarations is a common implementation detail.

**Comment by akumta** [comment]
Thank you.

**Pull request merged**
