### PR TITLE
Implement ostream_joiner

### PR DESCRIPTION
**Pull request by glenfe**

### CODE REVIEW

**Comment by Lastique** [comment]
This might be better placed in Boost.Iterator.

**Comment by glenfe** [comment]
Iterator is one obvious place for it. Utility has minimal dependencies though, and we have users that tend to favor those.

**Comment by Lastique** [comment]
I really don't like the idea of us putting components wherever there are least dependencies. We could put it in Boost.Core in that case. This is a sure way to having a total mess in Boost.

**Comment by glenfe** [comment]
Clearly that isn't the only criteria, to warrant "wherever". i.e. This single class template is as much a "utility" as, say, string_view.

**Comment by Lastique** [comment]
Well, it is much closer to Iterator than to Utility. `std::ostream_joiner` is even defined in `<iterator>`

If there are unnecessary dependencies in Boost.Iterator, maybe we could work on that.

PS: I'm not quite happy about `string_view` and some other components either. I'd prefer not to make it worse.

**Comment by pdimov** [comment]
Putting small things in Utility for dependency reasons isn't entirely wrong as a strategy. If we look at the standard library, `swap` was correctly moved to `<utility>`, and it would've been much better if `less` and `hash` were there too, instead of in `<functional>`.

In fact one might argue that this approach works against Utility becoming the mess it was before we cleaned it up - if the thing depends on this and that, it probably doesn't belong here.

**Comment by Lastique** [comment]
Standard library is a terrible example to follow, if you ask me. Its headers are so coarse-grained that people seriously consider rewriting portions of it or including its internal headers just to avoid including the proper headers. And this is not just a sign of inappropriate placement of components. Moving stuff around doesn't really help. I'm as reluctant to include `<utility>` just to get `swap` and `move` as I was to include `<algorithm>`, and I actually often prefer to replace `move` and `forward` with a `static_cast` for that reason.

Having components at their right place is good for users, as they are more likely to find the components they are looking for. It is also good maintenance-wise. It does not affect compile-time dependencies, as you're not introducing new includes. It may affect submodule-wise dependencies, but given that we're still distributing monolithic Boost and it is also delivered to users as a monolithic tree, that argument is rather weak.

**Comment by pdimov** [comment]
I'd recommend `io` for `ostream_joiner`, actually. That's exactly what `io` was for, but nobody remembers. Glen should just take over it and put all iostreams-related utilities there.

**Comment by glenfe** [comment]
IO sounds good to me. Will do.

**Pull request closed without merging**
