### PR TITLE
Simplify `value_initialized` definition

### PR DESCRIPTION
**Pull request by Kojoley**

### CODE REVIEW

**Comment by Lastique** [comment]
Is there a reason why we have two templates for this? Besides backward compatibility.

**Comment by Lastique** [comment]
@Kojoley Please, take a look at test failures.

**Comment by Kojoley** [comment]
I do not know, the `initialized` appeared later, the difference seems to be only in forwarding constructor. The only usage in the whole Boost of those facilities is MPL.

The compile fail in GCC 10 seems strange, there is no error message. The clang fails seems like unimplemented DR253, do we have a macro for it?

**Comment by Lastique** [comment]
> The clang fails seems like unimplemented DR253, do we have a macro for it?

I'm not aware of one.

**Comment by Kojoley** [comment]
Well, DR253 is not resolved, I learned something new today.

At this point I do not see much value in the patch, sorry for the noise.

**Pull request closed without merging**
