### PR TITLE
Cease dependence on ContainerHash

### PR DESCRIPTION
**Pull request by Kojoley**
by local `hash_range` forward declaration

### CODE REVIEW

**Comment by Lastique** [comment]
It is needed for `hash_range`.

**Comment by Kojoley** [comment]
Indeed. It is been not the first time I got hit by broken two-phase lookup on one famous platform...

**Comment by Kojoley** [comment]
Is there actually a reason why it includes forward header? May be turn that call to unqualified so we can remove the include?

**Comment by Kojoley** [comment]
I have pulled forward declaration and reopened the PR.

**Comment by Lastique** [comment]
I don't think duplicating the forward declaration is the right thing to do, that's why there is a forward header in the first place. But I'll let @mclow decide.

**Comment by Kojoley** [comment]
The thing is that you need to download the whole library just to use the forward declaration from it.

**Comment by Kojoley** [comment]
Ping? I found out that Boost.Array does it already for a long time https://github.com/boostorg/array/commit/cb4df41bd6bb64eead5e8d38b49716e7b681204c

**Comment by Kojoley** [comment]
@pdimov you've done the same change to Array in https://github.com/boostorg/array/commit/cb4df41bd6bb64eead5e8d38b49716e7b681204c, could you please take authority over this PR since I'm not getting any response from maintainers?

**Comment by pdimov** [comment]
I see nothing wrong with this PR (obviously) but I can't take authority over it, sorry. :-)

**Comment by mclow** [comment]
My feeling here is that the title of the PR is misleading: "Cease dependence on ContainerHash".
The dependency is not removed, just the include.  And by replicating the declaration, the code is made more brittle - if `hash_range` changes in the future, then user's code will (if they are lucky) fail to link.  If they're unlucky, then their code will crash at runtime.

**Comment by mclow** [comment]
I guess I'm not understanding the rationale here. What is the goal of this PR? 
I doubt that it's compile-time performance, since `hash_fwd.hpp` is very small.

**Comment by Kojoley** [comment]
> My feeling here is that the title of the PR is misleading: "Cease dependence on ContainerHash".
> The dependency is not removed, just the include.

The dependency on ContainerHash is removed for anyone who do not use `hash_range`.

> And by replicating the declaration, the code is made more brittle - if `hash_range` changes in the future, then user's code will (if they are lucky) fail to link. If they're unlucky, then their code will crash at runtime.

I doubt that, but anyway that's not a problem at all, both libraries are in Boost and could be fixed quickly.

> I guess I'm not understanding the rationale here. What is the goal of this PR?
> I doubt that it's compile-time performance, since `hash_fwd.hpp` is very small.

To not pull unneeded repositories https://github.com/boostorg/utility/blob/9ad7e519129c5e557b155b37c7fdb806d03609ca/CMakeLists.txt#L18

**Comment by pdimov** [comment]
It removes the physical dependency. To include the header, the contents of ContainerHash need to be physically present. This means that in the modular case the repo needs to be checked out.

**Comment by Lastique** [comment]
FWIW, in order to improve dependencies in general, I would've preferred if Boost.StringView was moved into its own submodule.

(As I noted before, I don't consider replicating forward declarations a good practice - not in terms of stability, scalability or maintainability.)

**Comment by Kojoley** [comment]
> (As I noted before, I don't consider replicating forward declarations a good practice - not in terms of stability, scalability or maintainability.)

Array is stable for these 7 years the change was committed. Forward declarations are the core part that makes C++ scalable. One change per 7 years is pretty maintainable. Also, your equation does not include users, but it is seems like a general line in the Boost lately.

**Comment by pdimov** [comment]
Libraries such as ContainerHash (and Serialization, and Json) should, ideally, provide a documented way of forward-declaring the necessary minimum that enables adding support for them without including a header.

**Comment by mclow** [comment]
> Libraries such as ContainerHash (and Serialization, and Json) should, ideally, provide a documented way of forward-declaring the necessary minimum that enables adding support for them without including a header.

That's what I thought that the point of 'hash_fwd.hpp' was.
Maybe header file shouldn't belong in 'container_hash'

**Comment by Kojoley** [comment]
Thanks for merging.

**Pull request merged**
