### PR TITLE
Adjust doxygen relative paths

### PR DESCRIPTION
**Pull request by alandefreitas**

### CODE REVIEW

**Comment by Lastique** [comment]
Is this why the docs on the website have no reference? Can we update the website?

**Comment by glenfe** [comment]
First let's see this reflected on the develop documentation build (should be about an hour or two): https://www.boost.org/doc/libs/develop/libs/utility/doc/html/index.html

If it's good, then we can do patch the generated 1.78 documentation on the website manually.

**Comment by Lastique** [comment]
The docs are updated, but still no reference.

**Comment by glenfe** [comment]
Yeah. :( Peter gave Alan some suggestions - we'll see how that works out.

**Comment by alandefreitas** [comment]
I'm building everything again with the [docker images](https://github.com/boostorg/release-tools/blob/master/docker/python2/bionic/Dockerfile). Let's see how that goes...

**Pull request merged**
